FROM python:3.10-slim
WORKDIR /app
COPY yolo_runner.py /app/
COPY input.jpg /app/
COPY input1.jpg /app/
COPY input2.jpg /app/
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 \
    && pip install --upgrade pip \
    && pip install ultralytics \